image:
- Visual Studio 2017
- Ubuntu

install:
- ps: |
    if ($isWindows) {
          vcpkg install gtest:x64-Windows
        } else {
          git clone https://github.com/Microsoft/vcpkg.git /home/appveyor/projects/vcpkg
          cd /home/appveyor/projects/vcpkg
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          (sudo apt-get update -y) -and (sudo apt-get install g++-7 -y) -and (sudo apt-get install make -y)
          (sh bootstrap-vcpkg.sh) -and (./vcpkg install gtest) -and (cd /home/appveyor/projects/shiva)
        }

build_script:
  - ps: |
      mkdir build
      cd build
      if ($isWindows) {
            cmake -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release -DSHIVA_BUILD_TESTS=ON -DSHIVA_BUILD_EXAMPLES=ON -G "Visual Studio 15 2017 Win64" ..
            cmake --build . --config Release -- /verbosity:minimal /maxcpucount:3
          } else {
            cmake -DCMAKE_TOOLCHAIN_FILE="/home/appveyor/projects/vcpkg/scripts/buildsystems/vcpkg.cmake" -DCMAKE_BUILD_TYPE=Release -DSHIVA_BUILD_TESTS=ON -DSHIVA_BUILD_EXAMPLES=ON ..
            cmake --build . --config Release
          }

test_script:
- ps: |
    ctest --no-compress-output -T Test -C Release
    cd ../bin
    if ($isWindows) {
      $filePattern = '*-test.exe'
    } else {
      $filePattern = '*-test'
    }
    if ($isWindows) {
      foreach ($file in get-ChildItem $filePattern)
      {
        $var = $file.name
        echo $var
        & ./$var --gtest_output="xml:$var-release-result.xml"
      }
    }
- sh: |
    for i in *-test; do
    	./$i --gtest_output="xml:${i}-release-result.xml" || exit 1
    done
- ps: |
    (cd ..) -and (mkdir test-result) -and (cd test-result) -and (mkdir ctest)
    (cd ..) -and (cp bin/*.xml test-result/) -and (cp build/Testing/*/*.xml test-result/ctest)

on_finish:
  - ps: |
      cd test-result/ctest
      $XSLInputElement = New-Object System.Xml.Xsl.XslCompiledTransform
      $XSLInputElement.Load("https://raw.githubusercontent.com/rpavlik/jenkins-ctest-plugin/master/ctest-to-junit.xsl")
      $XSLInputElement.Transform((Resolve-Path .\Test.xml), (Join-Path (Resolve-Path .) "ctest-to-junit-results.xml"))
      $wc = New-Object 'System.Net.WebClient'
      $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\ctest-to-junit-results.xml))
      echo "finish"