language: cpp

dist: trusty
sudo: false

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
             - ubuntu-toolchain-r-test
          packages:
             - g++-7
      env: COMPILER=g++-7 CXXSTD=17
    - compiler: gcc
      addons:
        apt:
          sources:
             - ubuntu-toolchain-r-test
          packages:
             - g++-8
      env: COMPILER=g++-8 CXXSTD=17
    - compiler: clang
      addons:
        apt:
          sources:
             - llvm-toolchain-trusty-6.0
             - ubuntu-toolchain-r-test
          packages:
             - clang++-6.0
             - libc++-dev
      env: COMPILER=clang++-6.0 CXXSTD=17

install:
    - git clone https://github.com/Microsoft/vcpkg.git && cd vcpkg && ./bootstrap-vcpkg.sh
    - ./vcpkg install gtest
    - export VCPKG_ROOT="$PWD" && echo $VCPKG_ROOT
    - if [ "$CXX" = "clang++" ]; then export CXX="$COMPILER -stdlib=libc++"; fi
    - if [ "$CXX" = "g++" ]; then export CXX="$COMPILER"; fi

script:
      ./scripts/run_unix.sh