language: cpp

dist: trusty
sudo: true

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
             - ubuntu-toolchain-r-test
          packages:
             - g++-7
      env: COMPILER=g++-7 CXXSTD=17

before_install:
    - if [ "$CXX" = "clang++" ]; then export CXX="$COMPILER -stdlib=libc++"; fi
    - if [ "$CXX" = "g++" ]; then export CXX="$COMPILER"; fi

install:
    - git clone https://github.com/Kitware/CMake.git && cd CMake && ./bootstrap && make -j2 && sudo make install
    - git clone https://github.com/Microsoft/vcpkg.git && cd vcpkg && cd toolsrc && mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Release .. && cd ../..
    - make -j2
    - ./vcpkg install gtest
    - export VCPKG_ROOT="$PWD" && echo $VCPKG_ROOT

script:
      ./scripts/run_unix.sh